PLUGIN_NAME=		vnstat-plus
PLUGIN_VERSION=		0.59
PLUGIN_COMMENT=	Extended VNStat dashboard widget
PLUGIN_MAINTAINER=	cguareschimd@gmail.com
PLUGIN_WWW=		https://github.com/claudioguareschi/opnsense-dashboard-plus
PLUGIN_DEPENDS=	os-vnstat

.include "../../Mk/plugins.mk"
