/*
 * Copyright (C) 2026 Claudio Guareschi <cguareschimd@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Everything the renderer writes on the map (legend, hover cards, flow sentences), in English.
 * Generated by scripts/generate-text.mjs from the widget's translations
 * (Metadata/FirewallMap.xml): edit the strings there, not here. The map page and the dashboard
 * widget pass their translated table to create() as `text`; a key they leave out falls back to
 * the English here. {name} marks a value filled in at run time; keys ending in _one / _many are
 * the singular and plural of one phrase.
 */
export const DEFAULT_TEXT = {
  geo_downloading_title: "Downloading the geolocation database",
  geo_preparing: "Starting the download…",
  geo_progress: "{done} of {total}",
  geo_fills_in: "The map fills in as soon as it is done.",
  geo_failed_title: "The geolocation database could not be downloaded",
  geo_key_title: "A MaxMind license key is needed",
  geo_key_advice: "Add it in the Firewall Map settings or in the GeoIP alias settings, or choose DB-IP Lite.",
  geo_retry_in: "Trying again in {time}",
  geo_retrying: "Trying again…",
  geo_retry_now: "Retry now",
  geo_settings: "Settings",
  geo_partial: "Network names are unavailable",
  geo_fallback: "Using {provider} Lite while the MaxMind download fails",
  geo_stale: "The geolocation database could not be updated",
  geo_err_unauthorized: "MaxMind did not accept the license key. A new key can take a few minutes to start working; if this persists, check the key in the settings and that GeoLite2 downloads are enabled for your MaxMind account.",
  geo_err_forbidden: "{provider} refused the download (HTTP 403): the account may not have access to this database.",
  geo_err_not_found: "{provider} did not have the database at the expected address (HTTP 404). DB-IP publishes a new file each month; early in the month it may not be out yet.",
  geo_err_rate_limited: "{provider} limits how often a database can be downloaded (HTTP 429).",
  geo_err_unreachable: "The firewall could not reach {provider}. Check that it has internet access and working DNS.",
  geo_err_timeout: "The download from {provider} took too long and was stopped. A slow or busy connection is the usual cause.",
  geo_err_invalid: "The downloaded file was not a valid database.",
  geo_err_disk_full: "The database could not be saved: the firewall's disk is full.",
  geo_err_http: "{provider} answered with an error.",
  geo_err_other: "The download failed.",
  map_ranking_bounded: "the busiest of {count} flows",
  map_ranking_warming: "ranking settling after a busy period",
  map_started_inside: "Outbound",
  map_started_outside: "Inbound",
  map_started_both: "Both directions",
  map_toward: "Mostly download",
  map_away: "Mostly upload",
  map_blocked: "Blocked",
  map_flagged_blocked: "Flagged · blocked",
  map_flagged_allowed: "Flagged · allowed",
  map_allowed: "Allowed",
  map_category_web: "Web",
  map_category_quic: "QUIC",
  map_category_dns: "DNS",
  map_category_ntp: "NTP",
  map_category_vpn: "VPN",
  map_category_mail: "Mail",
  map_category_remote_access: "Remote access",
  map_category_push_stun: "Push / STUN",
  map_category_other: "Other",
  map_seconds: "{count} s",
  map_minutes: "{count} min",
  map_hours: "{count} h",
  map_days: "{count} days",
  map_moments: "moments",
  map_port: "port {port}",
  map_traffic: "traffic",
  map_this_firewall: "this firewall",
  map_this_firewall_title: "This firewall",
  map_other_targets_one: "{target} (and {count} other target)",
  map_other_targets_many: "{target} (and {count} other targets)",
  map_open_for: ", open for {duration}",
  map_reached: "{other} reached {where} on {service}{open}.",
  map_reached_forward: "{other} reached {where} on {service} through a port forward{open}.",
  map_other_hosts_one: "{host} and {count} other host",
  map_other_hosts_many: "{host} and {count} other hosts",
  map_other_services_one: "{service} and {count} other service",
  map_other_services_many: "{service} and {count} other services",
  map_queried: "{who} queried {service} at {other}",
  map_synced: "{who} synced time with {other} over {service}",
  map_mailed: "{who} delivered mail to {other} over {service}",
  map_pinged: "{who} pinged {other}",
  map_opened: "{who} opened {service} to {other}",
  map_a_connection: "a connection",
  map_other_ports_one: "{services} and {count} other port",
  map_other_ports_many: "{services} and {count} other ports",
  map_two_services: "{first} and {second}",
  map_first_seen_ago: ", first seen {duration} ago",
  map_block_sentence: "{source}{place} tried {tried} on this firewall: blocked {hits}× in the last {minutes} min{since}.",
  map_block_sentence_rule: "{source}{place} tried {tried} on this firewall: blocked {hits}× in the last {minutes} min by \"{rule}\"{since}.",
  map_block_sentence_interface: "{source}{place} tried {tried} on this firewall: blocked {hits}× in the last {minutes} min on {interface}{since}.",
  map_block_sentence_rule_interface: "{source}{place} tried {tried} on this firewall: blocked {hits}× in the last {minutes} min by \"{rule}\" on {interface}{since}.",
  map_ids_line: "{signature} (severity {severity}{category})",
  map_ids_source: "Suricata: {line}",
  map_ids_first: ", {count}× in the last {window}, latest {latest} ago",
  map_ids_count: ", {count}×",
  map_more_alerts_one: "and {count} more alert",
  map_more_alerts_many: "and {count} more alerts",
  map_more_addresses_one: "+{count} more address here",
  map_more_addresses_many: "+{count} more addresses here",
  map_addresses_many: "{count} addresses",
  map_via: "via {egress}",
  map_open_state: "open for {duration}",
  map_closed: "closed",
  map_ips_dropped: "Dropped by IPS",
  map_ips_dropped_flagged: "Dropped by IPS · flagged",
  map_ids_connection: "Suricata alerted on this connection",
  map_ids_connection_dropped: "Suricata alerted on this connection · dropped by IPS",
  map_rule: "rule: {rule}",
  map_seen_by_suricata: "Seen by Suricata",
  map_seen_by_suricata_flagged: "Seen by Suricata · flagged",
  map_no_connection: "No connection is open right now",
  map_last_minute: "{count} in the last minute",
  map_last_minute_hammering: "{count} in the last minute · hammering",
  map_active_links_one: "{count} active link",
  map_active_links_many: "{count} active links",
};

/** The text table in use: the caller's translations over the English defaults. */
export function textTable(text) {
  return {...DEFAULT_TEXT, ...(text || {})};
}
