/*
 * Copyright (C) 2026 Claudio Guareschi <cguareschimd@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef FM_CONTEXT_H
#define FM_CONTEXT_H
#include "error.h"
#include <stdint.h>
#define FM_INTERFACE_SIZE 16
/* Address classification bits supplied by Python's R rows. */
#define FM_PUBLIC 1
#define FM_PRIVATE 2
/* Request maxima. L, N and A are operator context: exceeding them
 * refuses the sample. R and S are generated by the plugin: exceeding them is
 * a malformed request. */
#define CONTEXT_MAX_RANGES 1024
#define CONTEXT_MAX_LOCAL 4096
#define CONTEXT_MAX_NETWORKS 8192
#define CONTEXT_MAX_ASSIGNED 1024
#define CONTEXT_MAX_SERVICES 1024
struct addr {
  unsigned char af, b[16];
};
struct range {
  struct addr lo, hi;
  unsigned flags;
};
struct net {
  struct addr a;
  unsigned prefix;
  char device[FM_INTERFACE_SIZE];
};
struct assigned {
  struct addr a;
  char device[FM_INTERFACE_SIZE];
};
struct service {
  unsigned proto, port, group;
};
/* Lookup structures built by context_prepare from the rows Python sent. */
struct net_entry {
  struct addr masked;
  size_t order; /* position in Python's specificity order: the tie-break */
};
struct net_group {
  unsigned char af;
  unsigned prefix;
  struct net_entry *entries; /* sorted by masked address, then order */
  size_t count;
};
/* Python supplies classification ranges, lexical local-address order and
 * specificity-ordered networks; C never parses OPNsense configuration.
 * The row arrays are owned by the context (fm_* heap, context_destroy). */
struct context {
  struct range *ranges;
  size_t nr;
  struct addr *local; /* Python's lexical order: origin() tie-break */
  size_t nl;
  struct net *nets; /* most specific first; equal prefixes in ifconfig order */
  size_t nn;
  struct assigned *assigned;
  size_t na;
  struct service *services;
  size_t ns;
  char wan[FM_INTERFACE_SIZE];
  /* derived by context_prepare */
  struct addr *local_sorted, *wan_sorted;
  size_t nwan;
  const char **local_device; /* device of local[i], or NULL */
  struct net_group *groups; /* longest prefix first */
  size_t ngroups;
  struct service *services_sorted;
};
struct context *context_create(struct fm_error *);
void context_destroy(struct context *);
/* Appends one row, growing the array; false when the kind's maximum is
 * reached (the caller decides: refusal or malformed request). */
bool context_add_range(struct context *, struct range, struct fm_error *);
bool context_add_local(struct context *, struct addr, struct fm_error *);
bool context_add_net(struct context *, struct net, struct fm_error *);
bool context_add_assigned(struct context *, struct assigned, struct fm_error *);
bool context_add_service(struct context *, struct service, struct fm_error *);
/* Validates (ranges sorted and disjoint) and builds the lookup structures. */
bool context_prepare(struct context *, struct fm_error *);

bool address_equal(struct addr, struct addr);
/* O(log ranges): the flags of the range containing the address, or 0. */
unsigned address_flags(const struct context *, struct addr);
bool context_is_local(const struct context *, struct addr);
/* An address assigned to the primary WAN device. */
bool context_is_wan_address(const struct context *, struct addr);
/* The device of the most specific network containing the address, skipping
 * networks on `excluded` (may be NULL); Python's order breaks ties. */
const char *context_device(const struct context *, struct addr, const char *excluded);
/* Service group of (proto, port), 0 when ungrouped. */
unsigned context_service_group(const struct context *, unsigned proto, unsigned port);
#endif
