PLUGIN_NAME=		firewall-map
PLUGIN_VERSION=		0.52
PLUGIN_COMMENT=		Live geographic firewall flow visualization
PLUGIN_MAINTAINER=	cguareschimd@gmail.com
PLUGIN_WWW=		https://github.com/claudioguareschi/opnsense-dashboard-plus

.include "../../Mk/plugins.mk"
