PLUGIN_NAME=		dashboard-plus
PLUGIN_VERSION=		0.61.2
PLUGIN_COMMENT=		Eleven extended dashboard widgets
PLUGIN_MAINTAINER=	cguareschimd@gmail.com
PLUGIN_WWW=		https://github.com/claudioguareschi/opnsense-dashboard-plus
PLUGIN_DEPENDS=		dmidecode

.include "../../Mk/plugins.mk"
