###################################################################
# Local syslog-ng configuration filter definition [firewallmap].
###################################################################
filter f_local_firewallmap {
    program("firewallmap");
};
