/*
 * Copyright (C) 2026 Claudio Guareschi <cguareschimd@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * Writes src/text.js, the renderer's English strings, from the dashboard widget's translations
 * (src/opnsense/www/js/widgets/Metadata/FirewallMap.xml): one source for the words the widget,
 * the map page and the renderer share. The map_* and geo_* keys are the renderer's.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const metadata = path.join(here, '../../src/opnsense/www/js/widgets/Metadata/FirewallMap.xml');
const target = path.join(here, '../src/text.js');
const xml = fs.readFileSync(metadata, 'utf8');
const block = xml.slice(xml.indexOf('<translations>'), xml.indexOf('</translations>'));
const entities = {amp: '&', lt: '<', gt: '>', quot: '"', apos: "'"};
const strings = [...block.matchAll(/<((?:map|geo)_[a-z0-9_]+)>([^<]*)<\/\1>/g)]
  .map(([, key, value]) => [key, value.replace(/&(amp|lt|gt|quot|apos);/g, (_, name) => entities[name])]);
const header = fs.readFileSync(target, 'utf8').split('*/')[0] + '*/';
fs.writeFileSync(target, `${header}

/*
 * Everything the renderer writes on the map (legend, hover cards, flow sentences), in English.
 * Generated by scripts/generate-text.mjs from the widget's translations
 * (Metadata/FirewallMap.xml): edit the strings there, not here. The map page and the dashboard
 * widget pass their translated table to create() as \`text\`; a key they leave out falls back to
 * the English here. {name} marks a value filled in at run time; keys ending in _one / _many are
 * the singular and plural of one phrase.
 */
export const DEFAULT_TEXT = {
${strings.map(([key, value]) => `  ${key}: ${JSON.stringify(value)},`).join('\n')}
};

/** The text table in use: the caller's translations over the English defaults. */
export function textTable(text) {
  return {...DEFAULT_TEXT, ...(text || {})};
}
`);
console.log(`src/text.js: ${strings.length} strings`);
